// This file is generated by @tanstack/router-plugin during `npm run build`.
// This stub is only used before the first build and will be overwritten.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const routeTree: any = null
