import { createRouter } from '@tanstack/react-router'
// routeTree.gen.ts is generated by @tanstack/router-plugin during build
// @ts-ignore
import { routeTree } from './routeTree.gen'

/** Factory called by both the server handler and the client hydration. */
export function getRouter() {
    return createRouter({
        routeTree,
        defaultPreload: 'intent',
        scrollRestoration: true,
    })
}

declare module '@tanstack/react-router' {
    interface Register {
        router: ReturnType<typeof getRouter>
    }
}
